# -*- coding: utf-8 -*-
"""fish.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z1SiXQdSC5EZsvPGzazwAgjHPEfpl-pT
"""

!kaggle datasets download -d trainingdatapro/fish-tracking-dataset

!pip install kaggle -q

from google.colab import files

files.upload()

! cp kaggle.json ~/.kaggle/

! chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d trainingdatapro/fish-tracking-dataset

!unzip /content/fish-tracking-dataset.zip -d /content/

!pip install ultralytics -q

!yolo detect predict model=yolov8m.pt source="/content/images"

!pip install ultralytics==8.0.20

!yolo task=detect mode=predict model=yolov8n.pt conf=0.25 source='/content/images' save=true

from IPython import display
display.clear_output()

from ultralytics import YOLO
from IPython.display import display, Image

Image(filename='runs/detect/predict/02.jpg',height=500)

files.download("/content/runs/detect/predict2")

files.download("/content/images")

files.download("/content/runs/detect/predict2/04.jpg")

!zip -r /content/images.zip /content/images

!ls /content/

from google.colab import files
files.download('/content/images.zip')

!zip -r /content/predict2.zip /content/runs/detect/predict2

!ls /content/

from google.colab import files
files.download('/content/predict2.zip')

