# -*- coding: utf-8 -*-
"""Assignment1phase2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ci3Xsenq3RHyNk9gWiCCeX6y6xKpw58Y
"""

print("Hello Hacktech")

!pip install ultralytics -q

from google.colab import drive
drive.mount('/content/drive')

!yolo detect predict model=yolov8m.pt source="/content/drive/MyDrive/timepass/1.webm"

!ffmpeg -i {"/content/runs/detect/predict/1.avi"} -vcodec libx264 {"final1.avi"}

!yolo detect predict model=yolov8m.pt source="/content/drive/MyDrive/timepass/2.webm"

!ffmpeg -i {"/content/runs/detect/predict2/2.avi"} -vcodec libx264 {"final2.avi"}

!yolo detect predict model=yolov8m.pt source="/content/drive/MyDrive/timepass/3.webm"

!ffmpeg -i {"/content/runs/detect/predict3/3.avi"} -vcodec libx264 {"final3.avi"}

