# -*- coding: utf-8 -*-
"""graph.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZwDhXRR2ZjvdgaKUMrOjrXXOiyfxOT6N
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

path_to_csv_file = '/content/drive/MyDrive/movies.csv'
df = pd.read_csv(path_to_csv_file)

df.head()

import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV data into a DataFrame
path_to_csv_file = '/content/drive/MyDrive/movies.csv'
df = pd.read_csv(path_to_csv_file)


# Extract the "Year of Release" and "Metascore of Movie" columns
year_of_release = df["Year of Release"]
metascore = df["Metascore of movie"]

# Create a scatter plot
plt.figure(figsize=(10, 6))
plt.scatter(year_of_release, metascore, alpha=0.5)
plt.title("Year of Release vs. Metascore of movie")
plt.xlabel("Year of Release")
plt.ylabel("Metascore of movie")
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV data into a DataFrame
path_to_csv_file = '/content/drive/MyDrive/movies.csv'
df = pd.read_csv(path_to_csv_file)

# Group the data by "Year of Release" and calculate the average Metascore for each year
average_metascore_by_year = df.groupby("Year of Release")["Metascore of movie"].mean().reset_index()

# Create a bar graph
plt.figure(figsize=(12, 6))
plt.bar(average_metascore_by_year["Year of Release"], average_metascore_by_year["Metascore of movie"])
plt.title("Average Metascore by Year of Release")
plt.xlabel("Year of Release")
plt.ylabel("Average Metascore")
plt.xticks(rotation=90)
plt.grid(axis="y")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV data into a DataFrame
path_to_csv_file = '/content/drive/MyDrive/movies.csv'
df = pd.read_csv(path_to_csv_file)

# Group the data by "Year of Release" and calculate the average Metascore for each year
average_metascore_by_year = df.groupby("Year of Release")["Metascore of movie"].mean().reset_index()

# Create a bar graph
plt.figure(figsize=(12, 6))
plt.bar(average_metascore_by_year["Year of Release"], average_metascore_by_year["Metascore of movie"])
plt.title("Average Metascore by Year of Release")
plt.xlabel("Year of Release")
plt.ylabel("Average Metascore")
plt.xticks(rotation=45, fontsize=10)  # Rotate x-axis labels by 45 degrees and adjust font size
plt.grid(axis="y")
plt.tight_layout()  # Ensure labels fit within the figure
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV data into a DataFrame
path_to_csv_file = '/content/drive/MyDrive/movies.csv'
df = pd.read_csv(path_to_csv_file)

# Create a histogram of Metascores
plt.figure(figsize=(10, 6))
plt.hist(df["Metascore of movie"], bins=20, edgecolor="k")
plt.title("Distribution of Metascores")
plt.xlabel("Metascore")
plt.ylabel("Frequency")
plt.grid(True)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV data into a DataFrame
path_to_csv_file = '/content/drive/MyDrive/movies.csv'
df = pd.read_csv(path_to_csv_file)

# Count the number of movies released in each year
year_counts = df["Year of Release"].value_counts().sort_index()

# Create a bar plot
plt.figure(figsize=(12, 6))
plt.bar(year_counts.index, year_counts.values)
plt.title("Number of Movies Released by Year")
plt.xlabel("Year of Release")
plt.ylabel("Number of Movies")
plt.xticks(rotation=45)
plt.grid(axis="y")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV data into a DataFrame
path_to_csv_file = '/content/drive/MyDrive/movies.csv'
df = pd.read_csv(path_to_csv_file)

# Count the number of movies for each rating category
rating_counts = df["Movie Rating"].value_counts()

# Create a pie chart
plt.figure(figsize=(8, 8))
plt.pie(rating_counts, labels=rating_counts.index, autopct="%1.1f%%", startangle=140)
plt.title("Distribution of Movie Ratings")
plt.axis("equal")  # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

